### ISSUE TITLE
Support fish shell

### ISSUE THREAD

**Issue by kabouzeid** [kabouzeid/nvim-lspinstall#10]
Currently experiencing a similar problem with the fish shell:

When trying to install lua:
```
fish: Unsupported use of '='. In fish, please use 'set os $(uname -s | tr "[:upper:]" "[:lower:]")'.

[Process exited 123]
```
When trying to install python, vim or bash:
```
set: Erase needs a variable name

Standard input (line 1):
set -e
^

(Type 'help set' for related documentation)
fish: Unknown command: '[[ ! -f package.json ]]'
fish:
  [[ ! -f package.json ]] && npm init -y --scope=lspinstall || true
  ^

up to date, audited 2 packages in 793ms

found 0 vulnerabilities

[Process exited 0]
```

_Originally posted by @SandWoodJones in https://github.com/kabouzeid/nvim-lspinstall/issues/9#issuecomment-804467753_

**Comment by jameswalmsley** [comment]
I've set my vim config to use bash when running commands:

```
vim.o.shell = '/bin/bash'
```
Might be nicer to get lspinstall to run all scripts in bash directly though.

**Comment by jameswalmsley** [comment]
I've added #16 as a workaround to force the scripts to run in bash.

**Comment by kabouzeid** [comment]
Thanks, looks like a sound workaround for now! Will test this soon.

**Comment by jameswalmsley** [comment]
Its not 100% ideal. If someone tries to open another :terminal while a script is running they'll get bash instead of their usual setting.

There's also a discussion on neovim about this issue:
https://github.com/neovim/neovim/issues/2292
