### ISSUE TITLE
html and css lsp servers are running but no lsp completions 

### ISSUE THREAD

**Issue by siduck76** [kabouzeid/nvim-lspinstall#108]
I dont know what has changed today ,  html and css lsp's are running in the background but I dont see the lsp completions at all :( . Other lsp servers work fine tho.
![image](https://user-images.githubusercontent.com/59060246/124867364-98d72300-dfdb-11eb-8e4c-2d4ce66ca1de.png)

![image](https://user-images.githubusercontent.com/59060246/124869216-87dbe100-dfde-11eb-8869-e31cf058a6b0.png)

:LspInfo 

![image](https://user-images.githubusercontent.com/59060246/124867398-a9879900-dfdb-11eb-92cf-32b69d3b3c78.png)

![image](https://user-images.githubusercontent.com/59060246/124879728-2706d580-dfeb-11eb-8b30-4949f0662375.png)

**Comment by siduck76** [comment]
lsp.log for css lsp https://paste.sh/5-UsHUs5#I3UxDJq80WQYRuRCWcYbxWPp

**Comment by kabouzeid** [comment]
It works for me. Do you still have this problem?

**Comment by siduck76** [comment]
> It works for me. Do you still have this problem?

It worked with the same config before tho , but now I added capabilities option for both html/css lsps and it works .

**Comment by kabouzeid** [comment]
capabilities option?

**Comment by siduck76** [comment]
> capabilities option?

```local capabilities = vim.lsp.protocol.make_client_capabilities()
     capabilities.textDocument.completion.completionItem.snippetSupport = true```

and adding this in the setup              ```       capabilities = capabilities```

**Comment by kabouzeid** [comment]
Ah yes, some severs need that :)
