### ISSUE TITLE
omnisharp in LSPInstall dosn't works

### ISSUE THREAD

**Issue by Johan-Palacios** [kabouzeid/nvim-lspinstall#110]
I installed omnisharp in LSPInstall, but when I tried to use this language server, omnisharp doesn't works, because this not show the autocomplete, can you give me a solution.

Extra information: I have Ubuntu in WSL, and the others' language servers works very well.

**Comment by kabouzeid** [comment]
Probably duplicate of https://github.com/kabouzeid/nvim-lspinstall/issues/77

Will fix soon

**Comment by Johan-Palacios** [comment]
Is a bug?

**Comment by kabouzeid** [comment]
it's not lspinstall related. right now omnisharp config doesn't seem to be quite right

**Comment by Johan-Palacios** [comment]
Ah OK, I want to use the autosuggestions for cshap, do you know an alternative for omnisharp for LSP in vim?
