### ISSUE TITLE
Terraform not initiating for .tf files

### ISSUE THREAD

**Issue by lukeberry99** [kabouzeid/nvim-lspinstall#111]
Hi,

I have installed `terraform-ls` using `:LspInstall terraform` but then when I open a .tf file and run `:LspInstall` I get the following output

```
Configured servers: terraform, typescript
Neovim logs at: /home/luke/.cache/nvim/lsp.log

0 client(s) attached to this buffer: 

0 active client(s): 

Clients that match the filetype tf:
```

Any ideas?

**Comment by lukeberry99** [comment]
Apparently you also need the `hashivim/terraform` package installed.

**Comment by kabouzeid** [comment]
you just need filetype detection for terraform.

`:set filetype=terraform` would also work
