### ISSUE TITLE
Install `rust-analyzer` with `rustup` ? 

### ISSUE THREAD

**Issue by midnightexigent** [kabouzeid/nvim-lspinstall#112]
Prebuilt `rust-analyzer` binaries depend on shared libraries at runtime which can cause problems on older operating systems (I can't find the corresponding GitHub issue to link but I've had that happen on Centos 7)

Installing `rust-analyzer` with `rustup` solves those issues and is generally cleaner. It is now part of the `nightly` tool-chain and can be [installed](https://rust-analyzer.github.io/manual.html#rustup)/ran/uninstalled with

```bash
# install
$ rustup +nightly component add rust-analyzer-preview
# run
$ rustup run nightly rust-analyzer
# uninstall
$ rustup +nightly component remove rust-analyzer-preview
```

**Comment by kabouzeid** [comment]
Can rustup be used to install it into a specific directory?

**Comment by midnightexigent** [comment]
I don't think so but `rustup which --toolchain nightly rust-analyzer` will output the full path to the binary

**Comment by kabouzeid** [comment]
Then it doesn't fit with the goal of this plugin. This plugin is for installing language servers locally without side effects. If you know that you want the rustup version, then you can install it via rustup. There is no need for this plugin in this case.

**Comment by kabouzeid** [comment]
I understand the confusion. Please don't mistake my comment as being rude. It's just not the goal of this plugin :)

**Comment by midnightexigent** [comment]
ha, I see, well, it is possible to do something hacky like `env RUSTUP_HOME=$DIR rustup +nightly component add rust-analyzer-preview` and everything will be in $DIR. But that will create a whole nightly tool-chain in $DIR ~1gb just for rust-analyzer 

There's surely a cleaner way to do it, I might look into it, I will keep you posted
