### ISSUE TITLE
Tailwind LSP running but no intellisense

### ISSUE THREAD

**Issue by TheRagingLoser** [kabouzeid/nvim-lspinstall#113]
Firstly thank you for you time and effort you put into this plugin as it has been a big help for me setting up lsp in neovim.  
This issue I have found is that the Tailwind lsp is running however I get no intellisense when defining a class. I am working on a django project and tailwind is all setup with the following structure.  
.
├── .git/
├── .venv/
├── node_modules/
├── src/
└── static/
├── package.json
├── postcss.config.js
└── tailwind.config.js

I have set the "root_dir" setting to:  
lsp.util.root_pattern('tailwind.config.js'), lsp.util.root_pattern('tailwind.config.js', '.git', 'postcss.config.js') etc, but with no success. 

The only way I can get intellisense is if I place a html file right in the root next to the tailwind.config.js and edit it. 

I understand this is not an issue with nvim-lspinstall but just thought you might have some insight on how to fix.   

Regards

**Comment by TheRagingLoser** [comment]
Turns out TailwindCSS lsp wasn't recognising the htmldjango filetype so once I added the following to the setup it worked:

**init_options = { userLanguages = { htmldjango = "html" }**

**Comment by kabouzeid** [comment]
Thanks, I'll add that to the config so this will work out of the box for django soon :)
