### ISSUE TITLE
typescript lsp

### ISSUE THREAD

**Issue by jahn-mtg** [kabouzeid/nvim-lspinstall#12]
I ran :LspInstall typescript, says it installed properly. But when I open up a index.js lsp, doesn't work. I have lsp working on other types (docker, lua, bash). I even tried it with projects with package.json in the root but still nothing. What am I missing?

**Comment by kabouzeid** [comment]
What is the output of `:LspInfo`?

**Comment by EilifAkerjordet** [comment]
I have the same issue.
All other languages seem to work fine, and the client attaches just fine.

Output is:

`Configured servers: tailwindcss, latex, typescript, css, php, python, dockerfile, lua, json, vim, html, yaml, bash
 Neovim logs at: /Users/eilif/.cache/nvim/lsp.log

0 client(s) attached to this buffer:

0 active client(s):

Clients that match the filetype javascript:

Config: tailwindcss
cmd:               node ./tailwindcss-intellisense/extension/dist/server/index.js --stdio
cmd is executable: True
identified root:   None
custom handlers:   tailwindcss/getConfiguration
Config: typescript
cmd:               /Users/eilif/.local/share/nvim/lspinstall/typescript/./node_modules/.bin/typescript-language-server --stdio
cmd is executable: True
identified root:   None
custom handlers:`

**Comment by kabouzeid** [comment]
Thanks for the update.
According to https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/tsserver.lua project root is detection is done by looking for `tsconfig.json, package.json, jsconfig.json, .git`.
Closing this, as this is not `lspinstall related.

@jahn-mtg I might be able to help you with this if you post the output of your `:LspInfo` command :)
