### ISSUE TITLE
A promblem of pyright maybe comes from npm

### ISSUE THREAD

**Issue by TD-Sky** [kabouzeid/nvim-lspinstall#122]
Every time I open a python file, pyright would work for a short time and then strike. At the same time, `node` uses many resources of CPU. The following is the `lsp.log`:

```
[ START ] 2021-07-18T14:13:04+0800 ] LSP logging initiated
[ WARN ] 2021-07-18T14:13:04+0800 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:108 ]
"The language server python triggers a registerCapability handler despite dynamicRegistration set to false.
Report upstream, this warning is harmless"
[ WARN ] 2021-07-18T14:13:05+0800 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:404 ]
"Exception received when installing recursive file system watcher:
TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]:
The feature watch recursively is unavailable on the current platform, which is being used to run Node.js"
```

For first WARN , I have checked the issues of `neovim/neovim` which said that the `dynamicRegistration` was set to `false` in order to fix some problems before. So this WARN doesn't imply root cause.

For second WARN, I have tried out some method like using my npm to install pyright but it didn't work. I have no other solutions now.

**Comment by kabouzeid** [comment]
what os and machine are you on? It says "The feature watch recursively is unavailable on the current platform, which is being used to run Node.js"

**Comment by TD-Sky** [comment]
```
OS: Arch Linux x86_64
Host: Inspiron 7591
Kernel: 5.12.15-arch1-1
CPU: Intel i7-9750H (12) @ 4.500GHz
GPU: Intel CoffeeLake-H GT2 [UHD Graphics 630]
GPU: NVIDIA GeForce GTX 1650 Mobile / Max-Q
Memory: 510MiB / 15768MiB
```

Moreover, I use [The Recommanded Configuration](https://github.com/kabouzeid/nvim-lspinstall#advanced-configuration-recommended) as my configuration.

The version of npm is 7.17.0 .

**Comment by kabouzeid** [comment]
See if you can update nodejs (not npm). Not sure what else to try :/

**Comment by kabouzeid** [comment]
Closing this because it's not caused nor can be fixed by lspinstall.

**Comment by ac130kz** [comment]
https://stackoverflow.com/questions/61806341/how-to-fix-the-feature-watch-recursively-is-unavailable-on-the-current-platform
https://nodejs.org/docs/latest/api/fs.html#fs_caveats


@kabouzeid 
It seems that fs.watch isn't fully supported on Linux, `--poll` argument to the Node is a solution. I'm not sure how to add a new cmd argument to fix it just on Linux.
