### ISSUE TITLE
LspInstall yaml uses bash and not user specified shell

### ISSUE THREAD

**Issue by liaden** [kabouzeid/nvim-lspinstall#123]
I am using zsh so my `$SHELL` is /usr/bin/zsh, and in my init.vim, I have `set shell=zsh`. I have asdf set up to manage node which has the .default-npm-packages that includes yarn but I haven't bothered configuring bash for asdf. When I try to `LspInstall yaml`, it complains:
```
bash: line 1: yarn: command not found
bash: line 2: yarn: command not found
```
Could this use the user specified shell?

Edit: I can set up bash so that asdf is loaded correctly and yarn is found, just figured this may be helpful for future users too.

**Comment by kabouzeid** [comment]
Can't use the users shell. Could be something like fish that isn't even POSIX compliant

**Comment by jalberto** [comment]
@kabouzeid is there any recommendation in how to use `asdf` with LspInstall?

**Comment by kabouzeid** [comment]
No, I don't know what this is

**Comment by jalberto** [comment]
it is a version manager for languages, I guess same issues will happen with rbenv or pyenv or any other version manager as they use similar mechanism
