### ISSUE TITLE
Json is not executable

### ISSUE THREAD

**Issue by ashincoder** [kabouzeid/nvim-lspinstall#124]
How to reproduce the problem from neovim startup:

LspInstall json
Enter a json file error shows

Actual behaviour:

In entering the json file you will get a error saying vscode-json... not executable

Expected behaviour:

Don't show anything work out of the box

Health check
health#lspconfig#check
Checking language server protocol configuration

    INFO: lua: configuration checked.
    INFO: python: configuration checked.
    INFO: bash: configuration checked.
    INFO: typescript: configuration checked.
    ERROR: jsonls: The given command "vscode-json-language-server" is not executable.
    INFO: json: configuration checked.

LSP log

nothing crazy
[ START ] 2021-07-22T20:13:17+0530 ] LSP logging initiated
[ START ] 2021-07-22T20:57:37+0530 ] LSP logging initiated

The thing is that I don't know which file to make executable

**Comment by francisco285** [comment]
Check if you have `lspconfig['jsonls']` running on startup, nvim-lspinstall uses `json` as client name, so having both 'jsonls' and 'json' may mess it up. That's what was causing the issue for me (I didn't notice I had `jsonls` in my config :smile:)

**Comment by ashincoder** [comment]
Mm I see
