### ISSUE TITLE
Installing Java language server fails

### ISSUE THREAD

**Issue by AmeerTaweel** [kabouzeid/nvim-lspinstall#128]
## Environment Info

+ NeoVim version: NVIM v0.6.0-dev+65-g46009499a
+ OS: Ubuntu 21.04
+ Shell: Fish Shell v3.1.2
+ Terminal: Alacritty v0.9.0-dev

## How To Reproduce

+ Start NeoVim, with LSP-Install already installed via Packer
+ Run `:LspInstall java`
+ NeoVim exits (gets killed), by a `SIGABRT` signal (Image below)

![image](https://user-images.githubusercontent.com/20538273/126950705-5cbabccc-0387-4a8c-810c-0ad1e13132d3.png)

## Expected Behavior

It should install the Java language server with no issues.

## Expected Reason

It might be because the install script is designed for Bash, not Fish shell? I don't know I'm just guessing. Because Fish shell is the only suspicious part of my setup...

**Comment by robbyhorvath** [comment]
I am also having this problem and also use Fish.

**Comment by robbyhorvath** [comment]
I loaded into a terminal with bash and received the same error and crash.

**Comment by AmeerTaweel** [comment]
@robbyhorvath So the script has a bug no matter what the shell used... Interesting that it was not caught before.

**Comment by robbyhorvath** [comment]
@AmeerTaweel I have been having this issue for about a week or two and thought I just broke my NeoVim config with the update.

**Comment by 9ebd7134** [comment]
same

**Comment by 9ebd7134** [comment]
It's broken in v0.6.0. I had it work on 4.3, I'll give it a try in 0.5.-

**Comment by 9ebd7134** [comment]
It works on 0.5.-

**Comment by AmeerTaweel** [comment]
@9ebd7134 Interesting. I downloaded NeoVim v0.5 and ran `:LspInstall java` and got the same error and crash.
![image](https://user-images.githubusercontent.com/20538273/128627610-8e1de11a-ea32-4afd-be44-e56288fb33b3.png)

**Comment by 9ebd7134** [comment]
@AmeerTaweel +1 to you sir, i ran :version which outputted v0.6.0-dev. I tried it on v0.5.- And it doesnt work. (I think its a lua update. Many plugins which require lua don't work or don't function proplerly under v.0.5.- because of some lua updates. Also this does work on 0.4.3 as i mentioned)

**Comment by AmeerTaweel** [comment]
@9ebd7134 as you mentioned, most of my plugins don't work on versions prior to `v0.5`. But I got the error with `:LspInstall java` on both `v0.5` and `v0.6-dev`. What is the exact version of `v0.6-dev` that you use? We might be using a different one since there are tons of pre-releases.

**Comment by 9ebd7134** [comment]
Here is my version:

NVIM v0.6.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

---- 
I also found out that this does not work with lua as well. it exits the same way

**Comment by aaleman** [comment]
Hi!
I just uploaded a PR fixing this issue.
I hope this can solve your issues.

**Comment by jukrb0x** [comment]
> Hi!
> I just uploaded a PR fixing this issue.
> I hope this can solve your issues.

Please help, the problem still exists. my version of neovim is 0.5.1

![image](https://user-images.githubusercontent.com/15688641/134965006-633c3bc8-d8b4-4dca-a168-9dfad48cc8dc.png)

when opening a .java file, nvim propmts

![image](https://user-images.githubusercontent.com/15688641/134965078-f8174e6e-6627-4546-be92-48f7f7681e2d.png)

and

![image](https://user-images.githubusercontent.com/15688641/134965158-0edafd69-dcec-420a-8187-de566d67e216.png)

**Comment by aaleman** [comment]
> Please help, the problem still exists. my version of neovim is 0.5.1

The issue was  when we tried to generate the jdtls script from lua, But your issue (i think) is different.
AFIAK lunarvim uses the lspinstall instalaltion dir so both of them use the same lspinstall config.
MAybe you can remove the lspinstall dir (or maybe only the java folder) and try to install de java plugin again using LspInstall.


I had some issues using java 8 and jdlts, now I´m using java 11 perfectly.

**Comment by jukrb0x** [comment]
> > Please help, the problem still exists. my version of neovim is 0.5.1
> 
> The issue was when we tried to generate the jdtls script from lua, But your issue (i think) is different.
> AFIAK lunarvim uses the lspinstall instalaltion dir so both of them use the same lspinstall config.
> MAybe you can remove the lspinstall dir (or maybe only the java folder) and try to install de java plugin again using LspInstall.
> 
> I had some issues using java 8 and jdlts, now I´m using java 11 perfectly.

I just solved my problem, everything working fine now as I switch `$JAVA_HOME ` to jdk11, thanks for reply though.

Plus to LunarVim, I am currently under `rolling` branch with neovim 0.5.1, `:LspInstall java` is still now working correctly (abort and terminal session dead) but install lsp plugin for java (jdtls) manually should work out.

**Comment by kabouzeid** [comment]
Is this fixed now?

**Comment by jukrb0x** [comment]
> Is this fixed now?

I am using rolling branch, and it is not working in this branch I suppose.
