### ISSUE TITLE
Server considered installed even when installing fails 

### ISSUE THREAD

**Issue by nuno-silva18** [kabouzeid/nvim-lspinstall#141]
Hi,

After merging [my PR](https://github.com/kabouzeid/nvim-lspinstall/pull/136), I noticed you did some code cleanup on what I'd done (which makes sense, my code was full of tabs and pretty dirty 😅). But it seems that the bug was reintroduced with the cleanup!

From my understanding, when the code throws the error on line 18 `error("[nvim-lspinstall] Could not install language server for " .. lang)`, it immediately exits the function afterwards, and does not delete the directory.

The easiest solution would be just moving the directory deletion to an earlier line, and then throwing the error 😄 Hope this helps, and if you don't feel like solving this, I can throw together a quick PR (and all pretty this time!)

**Comment by kabouzeid** [comment]
That's what I get for not testing after clean up. Yes please make a new PR if you have time, sorry!

**Comment by nuno-silva18** [comment]
Don't worry about it, happens to the best of us 😄 I've created the [PR](https://github.com/kabouzeid/nvim-lspinstall/pull/144)
