### ISSUE TITLE
Can't install Python LSP using LspInstall, in WSL2

### ISSUE THREAD

**Issue by Binx-Codes** [kabouzeid/nvim-lspinstall#171]
So, i'm using WSL2 (on Windows 10) and whenever I try doing `:LspInstall python` in neovim I get this error:

![image](https://user-images.githubusercontent.com/68950943/134178896-e84b26f4-7c45-4053-85f0-59aa6ced8c5a.png)

Does anybody know how I can fix this?

**Comment by Arrow-x** [comment]
same on Manjaro Linux

**Comment by Binx-Codes** [comment]
@Arrow-x so looks like I had an old version of node. I installed v16.10.0 which is the most recent one available, and it fixed the issue. Hope that helps you out.
