### ISSUE TITLE
Custom install path

### ISSUE THREAD

**Issue by ranebrown** [kabouzeid/nvim-lspinstall#174]
Is there a way to change the install path location from `vim.stdpath("data")` to some other location?

**Comment by kabouzeid** [comment]
```lua
require'lspinstall/util'.install_path = function(lang)
  return "/your/abs/path" .. lang
end
```

might work. haven't tried it though

**Comment by ranebrown** [comment]
That did seem to work for the install but then I started getting errors about servers I don't even have installed.

```
cmd ["<install path>/lspinstall/./sumneko-lua-language-server"] is not executable.
cmd ["<install path>/lspinstall/./efm-langserver"] is not executable.
```
