### ISSUE TITLE
Java support

### ISSUE THREAD

**Issue by GustavoPrietoP** [kabouzeid/nvim-lspinstall#18]
do you guys plan on adding support for java? I feel like automating the process of getting java to work would be very very helpful since right now its kind of a pain to get java setup :smile:

**Comment by kabouzeid** [comment]
This is why it's not included yet. It seems like the eclipse jdtls depends very much on the users configuration.

**Comment by kabouzeid** [comment]
https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/jdtls.lua

**Comment by kabouzeid** [comment]
Duplicate of: https://github.com/kabouzeid/nvim-lspinstall/issues/3
