### ISSUE TITLE
Install a list of language servers at startup

### ISSUE THREAD

**Issue by nodo** [kabouzeid/nvim-lspinstall#180]
Hi there 👋 Thanks for the amazing project 🚀 

I was wondering, is there is a way to automatically install a list language servers at startup?

**Comment by derektata** [comment]
Currently, I don't think there is a way, and creating an auto prompt to install one also has some bugs, see issue: https://github.com/kabouzeid/nvim-lspinstall/issues/137

**Comment by nodo** [comment]
Thanks a lot 👍 Closing the issue as it's very similar to the other. I will update it if I find a workaround.

**Comment by derektata** [comment]
Not a problem man, It's something I've been working on in my spare time.
