### ISSUE TITLE
wget dependacy errors on mac

### ISSUE THREAD

**Issue by simonmclean** [kabouzeid/nvim-lspinstall#2]
Some `LspInstall <arg>` commands result in a call to `wget`. If this isn't installed (as it wasn't on my Mac) the process exits with the error

```
command not found: wget
```

I was able to install the typescript server just fine, but others (such as html) errored.

If this is a necessary dependacy I guess that should be documented? A simple `brew install wget` fixed the issue.

**Comment by kabouzeid** [comment]
Thanks for letting me know, I’ll replace wget with curl.
In the mean time you can install wget via brew just as you described.

**Comment by kabouzeid** [comment]
Turns out that it's safer to use wget for the download because cURL doesn't support recursive downloads. I'll add this to the readme.

**Comment by hemedani** [comment]
install `wget` with brew `brew install wget`

**Comment by kabouzeid** [comment]
Using `curl -L` would work to replace `wget`. I'll do this when I find some time for it :)

@hemedani yes this is true, but it's better to have fewer dependencies and `curl` is preinstalled on macOS :)

**Comment by hemedani** [comment]
I agreed, reduce the dependency is much better way
