### ISSUE TITLE
could not create directory

### ISSUE THREAD

**Issue by NTBBloodbath** [kabouzeid/nvim-lspinstall#20]
Hi, I don't want to be annoying but I really want to find a solution to the problem I'm having since I haven't seen it anywhere else and I'm really interested in using the plugin without having to patch it :sweat_smile:.

When running `:LspInstall lang` I get the error `could not create directory lang`. As I had thought about the PR that for some reason the command was being executed with my version of Lua, I downgraded to lua 5.1 to make sure it wasn't that, and the same problem continues.

In case this information is useful for something:
- Nvim version: `NVIM v0.5.0-dev+1177-g095f5da79`
- doing `os.execute("mkdir -p ".. path)` inside Neovim returns `true exit 0` as it would in newer versions of Lua (I don't understand why yet, if Lua 5.1 is supposed to be used in Neovim)

Thanks in advance :slightly_smiling_face:

**Comment by NTBBloodbath** [comment]
Nvm, I just saw that the compilation that Neovim recommends for nightly builds in Fedora apparently is not the same as the AppImage, now it works as it should!

Note for those who use the [agriffis copr](https://copr.fedorainfracloud.org/coprs/agriffis/neovim-nightly/): if you want to use this plugin, you will have to use the AppImage provided by Neovim instead.

**Comment by kabouzeid** [comment]
Thanks for following up on this!
