### ISSUE TITLE
Error installing efm

### ISSUE THREAD

**Issue by michalens** [kabouzeid/nvim-lspinstall#25]
I have the following error installing efm
```
package github.com/mattn/efm-langserver@HEAD: invalid github.com/ import path "github.com/mattn/efm
-langserver@HEAD"

[Process exited 1]
```

[Maintainer of efm said ](https://github.com/mattn/efm-langserver/issues/105#issuecomment-813078773)that it should not use `@HEAD`

**Comment by kabouzeid** [comment]
@michalens can you confirm that it's working now?

**Comment by michalens** [comment]
@kabouzeid unfortunately no. I get absolutely the same error but with `@latest` instead of `@HEAD`. Perhaps remove it altogether?

**Comment by kabouzeid** [comment]
Just testing something, what happens when you execute this in your shell `GO111MODULE=on go get golang.org/x/tools/gopls@latest`?

**Comment by kabouzeid** [comment]
Should work now. You probably have an old version of go (<1.15).
