### ISSUE TITLE
lspconfig can't load configs that were required by lspinstall

### ISSUE THREAD

**Issue by hrqmonteiro** [kabouzeid/nvim-lspinstall#27]
I installed the plugin, now it keeps accusing me of this error in every of my language config. Like, i had this:

```
require"lspconfig".html.setup {}
require"lspconfig".solargraph.setup {}
require"lspconfig".vimls.setup {}
require"lspconfig".cssls.setup {}
```

Then it appeared:

```
E5113: Error while calling lua chunk: /home/hrq/.config/nvim/lua/lsp/lspconfig.lua:39: attempt to index field 'sol
argraph' (a nil value)
Press ENTER or type command to continue
```

Then if i remove the solargraph line, it accused from the html, hen if i remove, it accuses for the vimls, and so on.

I removed all of them, now it's accusing the same on the sumneko_lua, which is configured like this:

```
local sumneko_root_path = vim.fn.stdpath('data') .. '/lspinstall/lua'
local sumneko_binary = sumneko_root_path .. '/sumneko-lua-language-server'

require'lspconfig'.sumneko_lua.setup {
    cmd = {sumneko_binary, "-E", sumneko_root_path .. "/main.lua"},
    on_attach = require'lsp'.common_on_attach,
    settings = {
        Lua = {
            runtime = {
                -- Tell the language server which version of Lua you're using (most likely LuaJIT in the case of Neovim)
                version = 'LuaJIT',
                -- Setup your lua path
                path = vim.split(package.path, ';')
            },
            diagnostics = {
                -- Get the language server to recognize the `vim` global
                globals = {'vim'}
            },
            workspace = {
                -- Make the server aware of Neovim runtime files
                library = {[vim.fn.expand('$VIMRUNTIME/lua')] = true, [vim.fn.expand('$VIMRUNTIME/lua/vim/lsp')] = true},
                maxPreload = 10000
            }
        }
    }
}
```

**Comment by kabouzeid** [comment]
You need to install https://github.com/neovim/nvim-lspconfig and you must rename this file `/home/hrq/.config/nvim/lua/lsp/lspconfig.lua`, otherwise `require'lspconfig'` will require your file instead of the nvim-lspconfig plugin.

**Comment by hrqmonteiro** [comment]
> You need to install https://github.com/neovim/nvim-lspconfig and you must rename this file `/home/hrq/.config/nvim/lua/lsp/lspconfig.lua`, otherwise `require'lspconfig'` will require your file instead of the nvim-lspconfig plugin.

I have this installed, i was using it perfectly before. All of the lspconfigs were working fine, actually.

**Comment by kabouzeid** [comment]
Yes I just saw that you have this file in a subfolder `/lsp/` so it's fine. In this case I need more context, could you share your whole lsp config file?

**Comment by pierreglaser** [comment]
Hi,
I'm hitting this issue as well. Lines like this:

https://github.com/kabouzeid/nvim-lspinstall/blob/6d1ebf24adf164ae7462b7d671a3c06841f9a88e/lua/lspinstall/servers/latex.lua#L2

are likely to be the reason behind it.

**Comment by vanhtuan0409** [comment]
Encounter the same error when trying to run `require'lspinstall'.setup()`

**Comment by vanhtuan0409** [comment]
https://github.com/vanhtuan0409/dotfiles/blob/lspinstall/config/nvim/lua/my_lsp/init.lua#L38

Seems like lspinstall replace `gopls` by `go` in lsp-config

**Comment by kabouzeid** [comment]
This is currently a limitation of nvim-lspconfig that I can't fix. When you have a language server installed with nvim-lspinstall, you must use the config provided by nvim-lspinstall, the old name is no longer valid.

e.g.

```lua
-- doesn't work
require"lspconfig".solargraph.setup {}
require"lspconfig".vimls.setup {}
require"lspconfig".cssls.setup {}
require"lspconfig".gopls.setup {}

-- instead use the name from `:LspInstall <name>`
require"lspconfig".rust.setup {}
require"lspconfig".vim.setup {}
require"lspconfig".css.setup {}
require"lspconfig".go.setup {}
```

**Comment by kabouzeid** [comment]
I recommend you to do it as described in the README https://github.com/kabouzeid/nvim-lspinstall#installation.

Or have a look at the `setup_servers` function in https://github.com/kabouzeid/nvim-lspinstall/wiki.

**Comment by kabouzeid** [comment]
Might be able to fix this in future by modifying [`package.loaded`](https://www.lua.org/manual/5.1/manual.html#pdf-package.loaded). On the other hand this isn't really a problem, because when you get this error, you should either uninstall the server, or change your config to use the installed server.

Let me know if any of you need help to setup :)

**Comment by vanhtuan0409** [comment]
In my case, some of the servers are installed using lspinstall, some are manually installed. Calling `require'lspinstall'.setup()` will throw error from manually installed servers. I think you should not unset servers that are not installed by lspinstall

**Comment by vanhtuan0409** [comment]
I think calling [available_servers](https://github.com/kabouzeid/nvim-lspinstall/blob/main/lua/lspinstall.lua#L86) will cause all default config unset even if it is not installed

**Comment by kabouzeid** [comment]
> In my case, some of the servers are installed using lspinstall, some are manually installed. Calling require'lspinstall'.setup() will throw error from manually installed servers. I think you should not unset servers that are not installed by lspinstall

Yes, you are right. I'll think about how to fix that.

> I think calling [available_servers](https://github.com/kabouzeid/nvim-lspinstall/blob/main/lua/lspinstall.lua#L86) will cause all default config unset even if it is not installed

No, but this line does: https://github.com/kabouzeid/nvim-lspinstall/blob/b2d11ef54b4862927b5c2e3b87aa962e8a517449/lua/lspinstall.lua#L1

> Btw why do you need to unset the default config? Can we just leave it there :D
When we don't unset it, nvim-lspconfig thinks we configured this config, and will try to load this config. It bloats the output of `:LspInfo`.

**Comment by kabouzeid** [comment]
@vanhtuan0409 finally found the time to fix this. Can you confirm that this works now in your case?

**Comment by vanhtuan0409** [comment]
Sorry I stopped using `lspinstall` recently so was unable to verify if it is working.

Will try to set it up again if I have time
