### ISSUE TITLE
Java and optional Lombok support

### ISSUE THREAD

**Issue by ChristianChiarulli** [kabouzeid/nvim-lspinstall#3]
Awesome plugin I definitely plan to use it.

Any plans to support Java?

**Comment by kabouzeid** [comment]
I'll look into it. What is the preferred language server for Java these days?

**Comment by ChristianChiarulli** [comment]
@kabouzeid This should be all you need to get started. Ping me if you want to discuss anything there, I've setup the langserver with Lombok a few times already. 

In the wiki there is a in depth config.

**Comment by jemag** [comment]
I think Christian forgot to paste a link.
Either way, https://github.com/mfussenegger/nvim-jdtls has a good guide on setting up the java language-server (you can check both the README and wiki). For lombok, the launch script can be modified like so by adding -javaagent -Xbootclasspath/a for your lombok jar path, e.g.:
``` sh
 #!/bin/bash

JAR="$HOME/dev/eclipse/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository/plugins/org.eclipse.equinox.launcher_*.jar"
export GRADLE_HOME=/usr/bin/gradle
java \
  -Declipse.application=org.eclipse.jdt.ls.core.id1 \
  -Dosgi.bundles.defaultStartLevel=4 \
  -Declipse.product=org.eclipse.jdt.ls.core.product \
  -Dlog.protocol=true \
  -Dlog.level=ALL \
  -Xms1g \
  -Xmx2G \
  -javaagent:/home/jemag/.config/nvim/dependencies/lombok.jar \
  -Xbootclasspath/a:/home/jemag/.config/nvim/dependencies/lombok.jar \
  -jar $(echo "$JAR") \
  -configuration "$HOME/dev/eclipse/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository/config_linux" \
  -data "$1" \
  --add-modules=ALL-SYSTEM \
  --add-opens java.base/java.util=ALL-UNNAMED \
  --add-opens java.base/java.lang=ALL-UNNAMED

```

**Comment by kabouzeid** [comment]
I don't think any of this will work in a way that fits with this plugin (install servers with one command).

I can't assume the location of `gradle`, `jdk` and `workspace`. Since you have to manually configure this server anyways, I don't think `:LspInstall java` would buy you much.

**Comment by kabouzeid** [comment]
@ChristianChiarulli @jemag @GustavoPrietoP @alanjjenkins I've merged support for Java + Lombok (with great help from @alanjjenkins). Could you try and tell me if this works for you?

**Comment by GustavoPrietoP** [comment]
> @ChristianChiarulli @jemag @GustavoPrietoP @alanjjenkins I've merged support for Java + Lombok (with great help from @alanjjenkins). Could you try and tell me if this works for you?

hey, i just tested it out and it seems like it works :)
