### ISSUE TITLE
LspInstall on windows can't create directory

### ISSUE THREAD

**Issue by kishikaisei** [kabouzeid/nvim-lspinstall#30]
Well basically running LspInstall with any languages throws this back:
`...ite\pack\packer\start\nvim-lspinstall\lua\lspinstall.lua:25: could not create directory latex function: builtin#18 ...ite\pack\packer\start\nvim-lspinstall\lua\lspinstall.lua:25: could not create directory json`
Is there a workaround, or is it "it's not working on MY machine" type of thing?

**Comment by kabouzeid** [comment]
Windows is not supported. Or do you mean WSL?

**Comment by kishikaisei** [comment]
WSL works fine. I just didn't find the mention that windows wasn't supported.
I guess it would be a good addition to the README?

**Comment by kabouzeid** [comment]
Will add it to the README

**Comment by fcomoreira1** [comment]
I have this same problem but on Fedora

**Comment by dedani** [comment]
I have the same problem on Opensuse Tumbleweed.

`:LspInstall python` results in:

`...ite/pack/packer/start/nvim-lspinstall/lua/lspinstall.lua:25: could not create directory python`

`:echo stdpath("data")` returns `/home/dani/.local/share/nvim` and looking into this directory (plus going down `lspinstall`) gives this:
`dani@huhu:~/.local/share/nvim/lspinstall$ ls /home/dani/.local/share/nvim/lspinstall/python/`

So the directory was successfully created! If I delete it or `lspinstall` it gets re-created with the exact same result.

**Comment by kabouzeid** [comment]
@dedani this is very weird. what is the return code of `mkdir -p /home/dani/.local/share/nvim/lspinstall/python/`?

**Comment by dedani** [comment]
`mkdir` exist with `0`.

```
dani@Chlinichiste:~$ ls ~/.local/share/nvim/lspinstall
dani@Chlinichiste:~$ rmdir ~/.local/share/nvim/lspinstall/python/
rmdir: failed to remove '/home/dani/.local/share/nvim/lspinstall/python/': No such file or directory
dani@Chlinichiste:~$ echo $?
1
dani@Chlinichiste:~$ mkdir -p ~/.local/share/nvim/lspinstall/python
dani@Chlinichiste:~$ echo $?
0
dani@Chlinichiste:~$ ls ~/.local/share/nvim/lspinstall
python
```

**Comment by dedani** [comment]
I tested with a simple config, only using packer, lspconfig and lspinstall. Same result. Is there something wrong with this setup? I'm absolutely new to lua and not very experienced with (Neo)Vim setups.

init.lua
```
-- Bootstrapping Packer
local execute = vim.api.nvim_command
local fn = vim.fn

local install_path = fn.stdpath('data')..'/site/pack/packer/opt/packer.nvim'

if fn.empty(fn.glob(install_path)) > 0 then
  execute('!git clone https://github.com/wbthomason/packer.nvim '..install_path)
  execute 'packadd packer.nvim'
end
--

vim.cmd [[packadd packer.nvim]]


-- install plugins
require("packer").startup(
  function()
    use {"wbthomason/packer.nvim"}
    use {"neovim/nvim-lspconfig"}
    use {"kabouzeid/nvim-lspinstall"}
  end
)

-- lspinstall
require('lspconfig')
require'lspinstall'.setup() 

local servers = require'lspinstall'.installed_servers()
for _, server in pairs(servers) do
  require'lspconfig'[server].setup{}
end
```

**Comment by dedani** [comment]
I modified the plugin such that the return code of `os.execute(mkdir -p .. path)` is not checked and the LSP gets then installed without a problem.
```
dani@lala:~/.config/nvim$ ls /home/dani/.local/share/nvim/lspinstall/python/node_modules/pyright/
dist  index.js  langserver.index.js  package.json  README.md
```

 It however still does not work since the LSP is not added/enabled. `:LspInfo` shows now available language server: `Configured servers: *nothing*`.

**Comment by dedani** [comment]
I think there is something more wrong than just `mkdir`. When I look at the plugin code, then on successfully install of a LSP is should print something like `Successfully installed " .. lang .. " language server!" or an error. But this never comes up on my system. The installation process stops here:
[pic](https://ibb.co/fdVv8Nh)

**Comment by kabouzeid** [comment]
There seems to be something wrong with lua's `os.execute` on your machine. Not sure why. I would recommend to install the latest neovim nightly if you haven't done so already.

Also what happens when you run `:lua print(os.execute("ls"))`?

**Comment by dedani** [comment]
I'm on the latest nightly, installed through the repositories provided by 
`https://download.opensuse.org/repositories/home:/ur4ltz:/neovim/openSUSE_Tumbleweed/` and `https://download.opensuse.org/repositories/home:/mcepl:/neovim/openSUSE_Tumbleweed/`. Both are on today's version and both have the same problems with `lspinstall`. I also tried `nvim.appimage` and the compiled binaries. All four versions returned, when running `:lua os.execute("ls")` the same thing: `ls: write error: Bad file descriptor". The used lua version is the same on all installs/images, tested with `:lua print(_VERSION)`: `Lua 5.1`

Funny enough, the versions from both repositories do not recognize the lsp for python installed previously (`:LspInstall python`). The installations did not really complete (hence the return code is not captured or so... see above). But the `appimage` version does recognize them and the lsp is activated and provides information.

**Comment by kabouzeid** [comment]
It should work now for you https://github.com/kabouzeid/nvim-lspinstall/commit/4257e3f91e3a08184ccedbece2352a0f7816bb23

Nonetheless there is definitely something wrong with your neovim installation.
Possibly related: https://github.com/kabouzeid/nvim-lspinstall/pull/13
