### ISSUE TITLE
Configure lsp Tailwind with Twin Marco

### ISSUE THREAD

**Issue by jjdechavez** [kabouzeid/nvim-lspinstall#45]
Hello everyone I'm working a project with [TailwindCSS](https://github.com/tailwindlabs/tailwindcss) and [Twin](https://github.com/ben-rogerson/twin.macro)

The problem is when I'm working with twin it doesn't display any lsp for tailwind
Sample code with Twin:
```js 
<div tw="text-lg font-medium text-gray-900">
```

And I saw on Vscode implmentation which need to [config](https://github.com/ben-rogerson/twin.macro/discussions/227#discussion-38611) their settings with 
```json
"scss.validate": false,
"editor.quickSuggestions": {
    "strings": true
},
"editor.autoClosingQuotes": "always",
"tailwindCSS.experimental.classRegex": [
    "tw`([^`]*)", // tw`...`
    "tw=\"([^\"]*)", // <div tw="..." />
    "tw={\"([^\"}]*)", // <div tw={"..."} />
    "tw\\.\\w+`([^`]*)", // tw.xxx`...`
    "tw\\(.*?\\)`([^`]*)" // tw(Component)`...`
],
"tailwindCSS.includeLanguages": {
  "typescript": "javascript",
  "typescriptreact": "javascript"
}
```
I'm wondering how do you guys implement this config on your lspconfig after you installed from lspinstall. TIA!

**Comment by kabouzeid** [comment]
TailwindCSS uses custom handlers to set those values, I've added support for this now b655450d38af28b037a33df583d54ebd7f043059.
You can now define those options as usual via the `settings` key of the lsp config.

```lua
require"lspconfig".tailwindcss.setup {
  settings = {
    tailwindCSS = {
      experimental = {
        classRegex = {
          "tw`([^`]*)", -- tw`...`
          "tw=\"([^\"]*)", -- <div tw="..." />
          "tw={\"([^\"}]*)", -- <div tw={"..."} />
          "tw\\.\\w+`([^`]*)", -- tw.xxx`...`
          "tw\\(.*?\\)`([^`]*)"
        }
      }
    }
  }
}
```

or equivalently you can set the `settings` key before
```lua
config = ...
config.settings = ...
require"lspconfig".tailwindcss.setup(config)
```

If you need more information on how to set the `settings` key in your config have a look at:
https://github.com/kabouzeid/nvim-lspinstall/wiki
https://github.com/neovim/nvim-lspconfig

**Comment by jjdechavez** [comment]
Thank you @kabouzeid !
