### ISSUE TITLE
Add GDScript installer

### ISSUE THREAD

**Issue by irishgreencitrus** [kabouzeid/nvim-lspinstall#49]
The server is supported [here](https://github.com/neovim/nvim-lspconfig) but can't be installed

**Comment by kabouzeid** [comment]
For which language is this?

**Comment by irishgreencitrus** [comment]
GDScript, language for the [Godot Game Engine](https://godotengine.org/)
It's in the supported languages it just can't be automatically installed.

**Comment by kabouzeid** [comment]
lspconfig and lspinstall are independent projects

**Comment by kabouzeid** [comment]
This is how you can add a custom installer to your config: https://github.com/kabouzeid/nvim-lspinstall#custom-installer

**Comment by irishgreencitrus** [comment]
Would this issue be better placed on the github page for the config I use?

**Comment by kabouzeid** [comment]
No, lspconfig doesn't provide installers. There is no issue, just add the installer to your local config :)
This project only provides installers for mainstream programming languages out of the box. Your expected to add your own installers for niche language servers. It's described how to do that here: https://github.com/kabouzeid/nvim-lspinstall#custom-installer
