### ISSUE TITLE
Snippets would be cool

### ISSUE THREAD

**Issue by ChristianChiarulli** [kabouzeid/nvim-lspinstall#5]
CoC regularly came with snippets, I have few on my GitHub for html Python Java you can checkout. 

VSCode has a native html one now we may be able to tap into.

vsnip supports all VSCode formatted snippets and would be nice to get everything working out of the box, although I could see how this may be a separate concern.

**Comment by kabouzeid** [comment]
I'm using this https://github.com/kitagry/vs-snippets with vsnips. Those are the snippets from VSCode and some extensions conveniently packed into one repo.

**Comment by kabouzeid** [comment]
Closing this because
1. snippets depend on the users completion plugin
2. not the scope of this plugin
