### ISSUE TITLE
jsonls doesn't correctly patch the command

### ISSUE THREAD

**Issue by tapayne88** [kabouzeid/nvim-lspinstall#54]
The jsonls installer sets up the command such that it won't get patched correctly on `require'lspinstall'.setup()`.

https://github.com/kabouzeid/nvim-lspinstall/blob/6657062a187ba172b89386a23b90c42f83691153/lua/lspinstall/servers/json.lua#L17

This looks to be a limitation of the setup function in that it only patches the first command. Appreciate I definitely lack the context but could we update the setup function to patch all relative paths in the command? Doing so would likely remove the need for #53

**Comment by kabouzeid** [comment]
Could you also move the whole method to the util.lua file?

**Comment by tapayne88** [comment]
Ah yes, this was me being foolish - my config was at fault! 🤦 

> Could you also move the whole method to the util.lua file?

Are you thinking this for #53?

**Comment by kabouzeid** [comment]
Oh, yes, I meant to write this on the PR 😅
