### ISSUE TITLE
scrolling tsx files causes errors

### ISSUE THREAD

**Issue by petertriho** [kabouzeid/nvim-lspinstall#61]
Whenever I scroll up (`<C-u>`) I see the following errors in tsx files
```
Error detected while processing WinScrolled Autocommands for "*":
E5108: Error executing lua Vim:E866: (NFA regexp) Misplaced {
```

**Comment by petertriho** [comment]
Issue seems to be related to something else. Still have the error when the ts lsp is removed

**Comment by kabouzeid** [comment]
if you don't have a `WinScrolled` autocmd in your config, then some plugin probably defines this. definitely not `lspinstall`

**Comment by petertriho** [comment]
Yep, seems like it was being caused by `folke/todo-comments.nvim`
