### ISSUE TITLE
"Client 1 quit with exit code 126 and signal 0" and "Client 1 quit with exit code 2 and signal 0" when opening/closing rust file.

### ISSUE THREAD

**Issue by Folaht** [kabouzeid/nvim-lspinstall#62]
## Setup 

Client 
- X86 Desktop
  - Manjaro OS XFCE
    - Alacritty 

Server computer - connectiion via ssh
- Raspberry Pi 4
  - Manjaro OS Minimal
    -  neovim
       -  lunarvim
          - nvim-lspinstall
          - rust-analyzer  

## Steps

1. Open a .rs file.
2. Close a .rs file.

First error appears when opening the rust file and the second one after closing the file.

*~/.cache/nvim/lsp.log*
```
...
[ ERROR ] 2021-05-17T20:23:43+0200 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	
"/home/folaht/.local/share/nvim/lspinstall/rust/rust-analyzer"	
"stderr""/home/folaht/.local/share/nvim/lspinstall/rust/rust-analyzer: 
/home/folaht/.local/share/nvim/lspinstall/rust/rust-analyzer: cannot execute binary file: Exec format error
...
```

**Comment by kabouzeid** [comment]
The script currently downloads the x86 binary. Someone needs to patch that.
