### ISSUE TITLE
Add haskell lsp

### ISSUE THREAD

**Issue by Matelasse** [kabouzeid/nvim-lspinstall#63]
https://github.com/haskell/haskell-language-server#vim-or-neovim

**Comment by sofubi** [comment]
It appears that the Haskell Language Server has been implemented but I have an issue with it. Currently running on Arch Linux I have `GHC 8.10.5` (the standard install) but the installed version from `nvim-lspinstall` is `GHC 8.10.4` causing a version mismatch error. Is there any way to amend this?

**Comment by cdimitroulas** [comment]
@sofubi I'm seeing the same issue, how did you fix it?
