### ISSUE TITLE
Windows 10 support

### ISSUE THREAD

**Issue by Borwe** [kabouzeid/nvim-lspinstall#69]
Is there a goal to add windows 10 support?

**Comment by kabouzeid** [comment]
Not right now. The plugin relies on shell scripts. It should work in WSL though

**Comment by Borwe** [comment]
Are pullrequests welcomed for such?

**Comment by kabouzeid** [comment]
As far as I know, the only way to achieve that would be to have separate shell script for unix and for Windows. I won't be able to maintain the Windows scripts, so no.
