### ISSUE TITLE
segfault on installing lua lsp

### ISSUE THREAD

**Issue by ellisonleao** [kabouzeid/nvim-lspinstall#7]
```
:LspInstall lua
Install lua language server?
[Y]es, (C)ancel: nvim: ../src/nvim/ui_compositor.c:564: ui_comp_raw_line: Assertion `attrs[i] >= 0' failed.
```

```
❯ nvim --version
NVIM v0.5.0-dev+1165-ge5bef5974
```

**Comment by kabouzeid** [comment]
Does this only happen with `lua`? I can't reproduce this.

**Comment by ellisonleao** [comment]
Yep, its happening with all lsp options, just tried it now

**Comment by kabouzeid** [comment]
Hmm, I have no idea what this could be, but this looks like a neovim bug to me. Maybe try updating to the latest neovim nightly :/

**Comment by ellisonleao** [comment]
https://github.com/neovim/neovim/issues/11240

it seems the issue is around the statusline, i just disabled it here and it worked again. I will close this for now but maybe others will still have the issue

**Comment by kabouzeid** [comment]
Thanks for reporting; hope you'll be able to properly fix this :)

**Comment by Flash1232** [comment]
> [neovim/neovim#11240](https://github.com/neovim/neovim/issues/11240)
> 
> it seems the issue is around the statusline, i just disabled it here and it worked again. I will close this for now but maybe others will still have the issue

yep, unfortunately :/ although it seems to work after removing lsp_status it is very impractical as a workaround. This seems to be the only plugin that conflicts for me...
