### ISSUE TITLE
Graphql LSP gives no autocomplete etc

### ISSUE THREAD

**Issue by NICHTJ3** [kabouzeid/nvim-lspinstall#70]
The graphql lsp appears to try look for a config in the install directory itself when it runs instead of the root directory. 
<img width="1435" alt="Screen Shot 2021-05-22 at 1 16 55 PM" src="https://user-images.githubusercontent.com/39316919/119210415-24febb00-bb00-11eb-8f6f-5e2ce49cfa58.png">
<img width="1541" alt="Screen Shot 2021-05-22 at 1 17 55 PM" src="https://user-images.githubusercontent.com/39316919/119210419-28924200-bb00-11eb-853b-dde73e51a570.png">

**Comment by kabouzeid** [comment]
Where is the config usually located?

**Comment by kabouzeid** [comment]
Thanks for the hint. Should work now. It'll look for the config in your project directory.
