### ISSUE TITLE
Issues with pyright autocompletion

### ISSUE THREAD

**Issue by Trid-collab** [kabouzeid/nvim-lspinstall#74]
I am newbie to python programing and lua version of init.lua for nvim. I am using nvim nightly on WSL2 - Ubuntu 20.04
I normally try learning using simple "*.py" files kept in a folders in in my Win 10 side - which get mounted on WSL by /mnt/c/Users/XXX/python_tutorial/. I have installed pyright server using "kabouzeid/nvim-lspinstall" plugin in my init.lua
Everything - autocomplete works well when I have .py file in WSL $HOME folder., but when I try to run nvim on .py file on my /mnt/c/Users/XXX/python_tutorial/ the auto complete doesn't work. This issue didn't happen when I used earlier init.vim with coc pyroght server install.

After some reading through your Readme on you site I put an requirement.txt or setup.py on the win10 python folder and then the autocomplete seemed to work. Could this be set to work like the coc pyright server where this was not required . It would save a lot of hassles for a learner like me who might keep multiple py folders as per learning and not necessarily doing a project with setup.py or requirements.txt

**Comment by kabouzeid** [comment]
Yes you can configure it like that, but it's not an issue of nvim-lspinstall. You have to set the `root_dir` value in the python config to something that fits your needs better.

These are the files that are used for python root dir detection by default: https://github.com/neovim/nvim-lspconfig/blob/240a9666f791c1eda91290f0b75ce0e428fbb355/lua/lspconfig/pyright.lua#L11-L15

You should read `:h lsp` and the documentation of [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig)
