### ISSUE TITLE
Omnisharp not working

### ISSUE THREAD

**Issue by kolpav** [kabouzeid/nvim-lspinstall#75]
I am very happy with this plugin it works great except for `csharp` it seems omnisharp server started and is accepting commands but for some reason non of them work. When trying go to definition it responds with just:

`
[ INFO ] 2021-05-23T14:19:54+0200 ] ...AD-0cbe748_2/share/nvim/runtime/lua/vim/lsp/handlers.lua:292 ] "textDocument/definition" "No location found"
`

Tested on project created with `dotnet new webapi --no-https`

Any idea what might be wrong?

**Comment by kolpav** [comment]
![image](https://user-images.githubusercontent.com/19467143/119260523-6b711a00-bbd3-11eb-82e2-5d55e6edadab.png)

**Comment by kabouzeid** [comment]
This is not lspinstall related. This is just using the config from nvim-lspconfig (https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/omnisharp.lua).

I just tried omnisharp with `dotnet new webapi --no-https` and it seems to be slow but (kinda?) working. I'm not sure, I don't know anything about dotnet.
go to definition works on some items for me.

I would install VSCode + omnisharp extension, open the project and see if it works there. Just to make sure it's not an omnisharp limitation

**Comment by kolpav** [comment]
I will try to create issue in `nvim-lspconfig` then, thanks.

**Comment by kabouzeid** [comment]
Honestly I think this is omnisharp related. Would recommend to try with VSCode first and see if it works there.

**Comment by kolpav** [comment]
Well it works in VSCode and even when using coc-omnisharp I'll try to investigate further to figure out if the issue is more appropriate for omnisharp.

**Comment by kolpav** [comment]
@kabouzeid Can I bring your attention to #77 I would like to know if my conclusions are correct or if I am doing something wrong.
