### ISSUE TITLE
Trigger autocompletion on `class: ""`

### ISSUE THREAD

**Issue by marcushwz** [kabouzeid/nvim-lspinstall#80]
Hi, thank you so much for this plugin. I was researching on how can I get tailwind intellisense working with neovim and found this. I manage to get tailwind working fine in a Ruby on Rails project but it only triggers the autocompletion when I do the normal `class=""` way.

```html
<a href="#" class="">Home</a>
```
![image](https://user-images.githubusercontent.com/40255418/120101966-726fcd80-c17b-11eb-9ede-613f9cabdf6c.png)

## Question
- Is it possible to add regex matching to trigger the autocompletion? I want to trigger autocompletion also when I do something like `class: ""`.
- I am working on a Rails project, and Rails have some helper method to do a link, for example:
```html
<%= link_to "Home", home_path, class: "" %>
```
![image](https://user-images.githubusercontent.com/40255418/120102047-ce3a5680-c17b-11eb-9462-eb9e9e2e7562.png)

**Comment by marcushwz** [comment]
Found the solutions.

**Comment by kabouzeid** [comment]
If someone is looking for this in future:

https://github.com/kabouzeid/nvim-lspinstall/issues/45#issuecomment-826902941

**Comment by marcushwz** [comment]
Hi, with lspconfig added support for tailwindcss, does this settings below still work? I can't seem to get it work now

```lua
require'lspconfig'.tailwindcss.setup{
  settings = {
    tailwindCSS = {
      experimental = {
        classRegex = {
          "class: \"([^\"]*)" -- <div class: "..." />
        }
      }
    }
  }
}

```

**Comment by marcushwz** [comment]
Hi, with nvim lspconfig added support for tailwindcss, does the settings below still work? I can't seem to get it work now

```lua
require'lspconfig'.tailwindcss.setup{
  settings = {
    tailwindCSS = {
      experimental = {
        classRegex = {
          "class: \"([^\"]*)" -- <div class: "..." />
        }
      }
    }
  }
}

```
