### ISSUE TITLE
How would I use this with folke/lua-dev.nvim

### ISSUE THREAD

**Issue by DanKGooGLy** [kabouzeid/nvim-lspinstall#89]
I've been scratching my head for the past half a day wondering how I could use [folke/lua-dev.nvim](https://github.com/folke/lua-dev.nvim) with the lua server installed by lspinstall.

**Comment by budswa** [comment]
How did you do it?

**Comment by DanKGooGLy** [comment]
https://github.com/folke/lua-dev.nvim/issues/15

**Comment by kabouzeid** [comment]
@budswa https://github.com/folke/lua-dev.nvim/issues/15#issuecomment-903878850
