### ISSUE TITLE
Adding a bit more documenttation regarding how to install language servers.

### ISSUE THREAD

**Issue by g96k** [kabouzeid/nvim-lspinstall#91]
First let me say the plugin is great.  

It would tremendously help if you could explain to the noobs like us what exactly the **cmd** and the **cmd is executable** expect

![image](https://user-images.githubusercontent.com/69681813/122476296-99792c80-cfce-11eb-8ff8-78e2f684b207.png)

![image](https://user-images.githubusercontent.com/69681813/122477362-42745700-cfd0-11eb-9c84-ce08f167e869.png)

For example here done lsp install tsserver and java

**Comment by kabouzeid** [comment]
This is not part of lspinstall but part of lspconfig :)
