### ISSUE TITLE
with latest neovim 0.5.0, this error was noticed

### ISSUE THREAD

**Issue by antonyr** [kabouzeid/nvim-lspinstall#94]
With the latest Neovim 0.5.0, This error was noticed.
```
E5108: Error executing lua ...ny/.nvim/plugged/nvim-lspinstall/lua/lspinstall/util.lua:11: attempt to index a nil value
```

Please help fix this.

**Comment by puhoy** [comment]
i see the same error, and it seems to have something to do with the setup of additional language servers. 
i added a config for pyls before, and when i remove it, the error disappears. 

```
-- pyls config
local config = require"lspinstall/util".extract_config("pyls")
config.default_config.cmd[1] = "./venv/bin/pyls"

require'lspinstall/servers'.python = vim.tbl_extend('error', config, {
  install_script = [[
  python -m venv ./venv
  ./venv/bin/pip install -U pip
  ./venv/bin/pip install -U 'python-language-server[all]'
  ./venv/bin/pip uninstall yapf autopep8
  ./venv/bin/pip install -U 'pyls-black'
  ./venv/bin/pip install -U 'pyls-mypy'
  ]]
})
```

this should look like the custom installer described in the [readme](https://github.com/kabouzeid/nvim-lspinstall#custom-installer) - did the setup change somehow?

**Comment by puhoy** [comment]
turns out, there was just no default config for pyls anymore.
(see https://github.com/neovim/nvim-lspconfig/pull/1074)
switched to pylsp, and its working again.
maybe its something similar for you @antonyr ?

**Comment by antonyr** [comment]
@puhoy I was not using pyls. But this error didn't occur after I rebuilt neovim on my M1 from scratch.
