### ISSUE TITLE
Lsp server request : CCLS 

### ISSUE THREAD

**Issue by siduck76** [kabouzeid/nvim-lspinstall#99]
https://github.com/MaskRay/ccls

**Comment by kabouzeid** [comment]
We already have clangd

**Comment by siduck76** [comment]
@kabouzeid  ccls gives better completions 

clangd 

![image](https://user-images.githubusercontent.com/59060246/123363916-20ab3f00-d591-11eb-91ae-95d82e5aef91.png)

ccls 
![image](https://user-images.githubusercontent.com/59060246/123364196-a6c78580-d591-11eb-9952-786d18b80c31.png)

**Comment by kabouzeid** [comment]
Can't compare this with only one example, I had the opposite experience for example. Not saying clangd is better than ccls or vice versa, but I only want to *bundle* one C/C++ language server, and in my personal experience clangd worked better.

This library is opinionated regarding the bundled language servers. If possible I only want to bundle a single language server per language, which should be the "best" default choice for this language.

I would consider swapping clangd for ccls if it was clearly way better, but as I said I don't think this is the case.

Of course if you prefer ccls you can just add the installer to your local config :)

**Comment by krishnakumarg1984** [comment]
> Of course if you prefer ccls you can just add the installer to your local config :)

@kabouzeid In your README.md (or in the project's wiki page), can you please show how to do this? i.e. install ccls through local config.

**Comment by kabouzeid** [comment]
https://github.com/kabouzeid/nvim-lspinstall#custom-installer
